all:
  children:
    soc:
      hosts:
        srv-wazuh:
          ansible_host: 10.0.2.20
          ansible_user: root
    network_devices:
      hosts:
        fw-opn01:
          ansible_host: 10.0.1.254
          ansible_user: root
    dmz:
      hosts:
        srv-dmz:
          ansible_host: 10.254.0.10
          ansible_user: cyna
          ansible_ssh_private_key_file: ~/.ssh/dmz_key
          ansible_become: true
          ansible_become_method: sudo
    zabbix_linux:
      hosts:
        srv-wazuh:
        srv-dmz:
