all:
  children:
    soc:
      hosts:
        srv-wazuh:
          ansible_host: 10.0.2.20
          ansible_user: root
    
    # Nouveau groupe pour tes équipements réseau
    network_devices:
      hosts:
        fw-opn01:
          ansible_host: 10.0.1.254
          ansible_user: root
          # Note: Pour le module opnsense, les clés API seront 
          # gérées en variables de groupe ou via un coffre-fort (Ansible Vault)
